config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to @article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render("form") %>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>
  <div class="row">
   <% @articles.each do |article| %>
    <div class="col-md-12">
      <h2><%= link_to article.title, article %></h2>
      <p> <%= article.content %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render("form") %>

app/views/articles/show.html.erb
<div class="container">
  <h1><%= @article.title %> <%= link_to "edit", edit_article_path(@article) %> | <%= link_to "delete", article_path(@article), method: "delete"  %>  </h1>
  <p><%= @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>